name: user_repo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^3.2.0
  cached_network_image: ^3.2.0
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flash: ^1.5.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^4.2.0
  fpdart: ^0.0.12
  freezed_annotation: ^0.14.2
  hooks_riverpod: ^1.0.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  oauth2: ^2.0.0
  path: ^1.8.0
  path_provider: ^2.0.2
  sembast: ^3.1.0+2
  shimmer: ^2.0.0
  webview_flutter: ^2.0.8

dev_dependencies:
  auto_route_generator: ^3.2.0
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  json_serializable: ^6.1.1
  lint: ^1.5.3

flutter:
  uses-material-design: true
